---
RecipeFormatVersion: '2020-01-25'
ComponentName: Blackbird.kvs.connector
ComponentVersion: 1.0.3
ComponentDescription: Greengrass component for KVS
ComponentPublisher: Blackbird
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        aws.iot.edgeConnectorForKVS:mqttproxy:1:
          policyDescription: "Allows access to subscribe to SiteWise Measurement IoT topic"
          operations:
            - 'aws.greengrass#SubscribeToIoTCore'
          resources:
            - '$aws/sitewise/asset-models/+/assets/+/properties/+'
    SiteWiseAssetIdForHub: ''
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ">= 2.0.3"
    DependencyType: HARD
  aws.greengrass.StreamManager:
    VersionRequirement: ">= 2.0.9"
    DependencyType: HARD
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://greengrass-component-artifacts/Blackbird.kvs.connector/1.0.3/EdgeConnectorForKVS-1.0-super.jar"
    Lifecycle:
      Run:
        Script: java -jar {artifacts:Path}/Blackbird.kvs.connector/EdgeConnectorForKVS-1.0-super.jar '{configuration:/SiteWiseAssetIdForHub}'