---
RecipeFormatVersion: '2020-01-25'
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: Greengrass component for KVS
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        aws.iot.edgeConnectorForKVS:mqttproxy:1:
          policyDescription: "Allows access to subscribe to SiteWise Measurement IoT topic"
          operations:
            - 'aws.greengrass#SubscribeToIoTCore'
          resources:
            - '$aws/sitewise/asset-models/+/assets/+/properties/+'
    SiteWiseAssetIdForHub: ''
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ">= 2.0.3"
    DependencyType: HARD
  aws.greengrass.StreamManager:
    VersionRequirement: ">= 2.0.9"
    DependencyType: HARD
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/EdgeConnectorForKVS-1.0-super.jar"
        Unarchive: NONE
    Lifecycle:
      Run:
        Script: java -jar {artifacts:path}/EdgeConnectorForKVS-1.0-super.jar '{configuration:/SiteWiseAssetIdForHub}'